#!/bin/bash
#
# update_eip         Start/Stop the cron clock daemon.
#
# chkconfig: 2345 99 60

export EC2_HOME=/opt/aws/apitools/ec2
export JAVA_HOME=/usr/lib/jvm/jre


eip="52.44.28.27"

function attch_EIP() {
    instance="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
    echo "INFO: attch $eip to ${instance}..."
    err=$(/opt/aws/bin/ec2-associate-address -i ${instance} ${eip} 2>&1)
    if [ $? -ne 0 ]; then
        echo "ERROR: during attching EIP ${err}"
        exit 1
    fi
    echo "INFO: successfully attaching EIP"
}


function detach_EIP() {
    echo "INFO: detach $eip"
    err=$(/opt/aws/bin/ec2-disassociate-address ${eip} 2>&1)
    if [ $? -ne 0 ]; then
        echo "ERROR: during attching EIP ${err}"
        exit 1
    fi
    echo "INFO: successfully attaching EIP"
}


param=$1

if [ "start" == "$param" ] ; then
    echo "INFO: start attching EIP..."
    attch_EIP
    exit 0
elif [ "stop" == "$param" ] ; then
    echo "INFO: stopping ${0}  no action..."
    detach_EIP
    exit 0;
else
    echo "don't know command $param.  only 'stop' and 'start' are valid"
    exit 1
fi

